Reason: Unknown - please refer to Cause below.
Cause: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at MySQLDatabase.connect(MySQLDatabase.java:71)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at MySQLDatabase.connect(MySQLDatabase.java:71)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:18)
Reason: Unknown - please refer to Cause below.
Cause: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at MySQLDatabase.connect(MySQLDatabase.java:70)
	at main.main(main.java:46)
Reason: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Cause: java.sql.SQLException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Reason: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Cause: java.sql.SQLException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Reason: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Cause: java.sql.SQLException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Reason: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Cause: java.sql.SQLException: The server time zone value 'WAT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:260)
	at java.base/java.lang.String.valueOf(String.java:3056)
	at User.<init>(User.java:53)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:260)
	at java.base/java.lang.String.valueOf(String.java:3056)
	at User.<init>(User.java:53)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: Unknown - please refer to Cause below.
Cause: null

java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:662)
	at java.base/java.lang.Long.parseLong(Long.java:824)
	at User.<init>(User.java:57)
	at main.main(main.java:20)
Reason: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

Reason: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

